# -*- coding: utf-8 -*-
"""data_fetcher.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139w21tNjqDtFq_zKpXvSiVLsg2WlCTP0
"""

import os
import requests
import pandas as pd
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

CSV_PATH = "/content/drive/MyDrive/Satellite_Imagery_Property_Valuation/data/raw/train(1)(train(1)).csv"
IMAGE_DIR = "/content/drive/MyDrive/Satellite_Imagery_Property_Valuation/data/images/satellite_images"
#deciding path to save satellite images

os.makedirs(IMAGE_DIR, exist_ok=True)

BBOX_SIZE = 0.002
ESRI_URL = (
    "https://services.arcgisonline.com/ArcGIS/rest/services/"
    "World_Imagery/MapServer/export"
)
#using esri api to extract satellite images for each data point in table

def fetch_satellite_image(lat, lon, property_id):

    min_lon = lon - BBOX_SIZE
    min_lat = lat - BBOX_SIZE
    max_lon = lon + BBOX_SIZE
    max_lat = lat + BBOX_SIZE

    bbox = f"{min_lon},{min_lat},{max_lon},{max_lat}"

    params = {
        "bbox": bbox,
        "bboxSR": 4326,
        "imageSR": 4326,
        "size": "224,224",
        "format": "png",
        "f": "image"
    }

    response = requests.get(ESRI_URL, params=params, timeout=20)

    if response.status_code == 200:
        image_path = os.path.join(IMAGE_DIR, f"{property_id}.png")
        with open(image_path, "wb") as f:
            f.write(response.content)
    else:
        print(f" Failed for ID {property_id}")

def main():

    df = pd.read_csv(CSV_PATH)
    print(f"Total properties: {len(df)}")

    required_cols = ["id", "lat", "long"]
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Missing column: {col}")

    for _, row in tqdm(df.iterrows(), total=len(df)):
        property_id = row["id"]
        lat = row["lat"]
        lon = row["long"]

        image_path = os.path.join(IMAGE_DIR, f"{property_id}.png")

        if os.path.exists(image_path):
          continue


        fetch_satellite_image(lat, lon, property_id)

if __name__ == "__main__":
    main()

"""### Showing extracted image

"""

from PIL import Image
import matplotlib.pyplot as plt
import os

img = Image.open(os.path.join(IMAGE_DIR, os.listdir(IMAGE_DIR)[0]))
plt.imshow(img)
plt.axis("off")
plt.show()

#so a folder has been created where images are extracted for each data point considering its latitude and longtitude

